language: r
sudo: false
install:
  - make

branches:
  only:
    - master
script:
  - bash ./deploy.sh

before_install:
  - echo $key_secret_password | gpg --passphrase-fd 0 deploy_key.gpg
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"

env:
  global:
    secure: "piAIrrzVeqB0wPGmwx2VH82qjBGLreg44PJkPNve36jzpAxZ6pt0EJlwF3Gs8EB3BX9Su1HGaQqj1ZGO5KQCd1gPlG7A3KXcS9HLG6Ls7gBiItMZVJHmR298PRbEeX55kDukZSQVfPY2ti+Ihoh+QeXYuC7ajXQccoBoYbs4q/97WS7/2/YroXmUsjNv6Nvab96PfLDoK9RMc6Ed0Led4KBJsMc01H/soU476gHMaK376ppc3YprGbxxanCaZ1c7rCaI8fHb/FcZeIaAWmQB5YnJLEb3BsYh0uhv8O2c/BDU/yBJj75bUO8c1vfOMIuzVU7j8fzFg1g4ok9VlbuHDJKlmIn5jXxFSIv+Q1cCQn0xIyQRKKFZyZucJuAxPat/DDqZW0HcytPG9GBImS7ssSMJqx+L2E1Ruz0mpzxjAiH0ekqrOUJ3M+7hQ3ZS1u2ApiC63I9VimhmSltbVNH/uDEzOE385QIKzRhn1b3ckymJ2DbAgE7k9I97BzUMll27k2pBPNtw49FlM/84ijFPDlb7cwX/KBB3udGzzp/zwA38GCKt4fj6UQ+GJ0UnRUAfSxu76QJdRI5f/Aq/VTpD2T1zgmsa2RMPdOgVJ5mUuzqnmB8c3rL4sGFgtLNIB3FNz+WbUeQxZWj+9/Ohlt9QVXXlCKJ1Cg8kEUgESqPWvGk="
