language: r
sudo: false
install:
  - make

branches:
  only:
    - master
script:
  - bash ./deploy.sh

before_install:
  - echo $key_secret_password | gpg --passphrase-fd 0 deploy_key.gpg
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"

env:
  global:
    secure: "fnIlHMV41MRlNiCm/wcETRiYGPgTiSM8953kF0sY8VNs7Kqg0pfWAOUDUoPfhnfhyVQ2CoxS5/b14cPfx9zlKD/X7XRx3yeG5HqmImU6ywpFkUAhXrpSJxTS1n4V1NyQlX8Fb94KgJS0Lk7c4LyGbL3BDr7Ut/BkXnAnUjW40wEWRR7RIoFEC/1UWGmkaQgWQCqIyZhoG93xWwcI8Qn6rxLkLfT9jlQvqXaAxEY+cPeQXPb/XHrw8UqtVeCdsGrkq+RCUET7QMCo+zfRPa2s70BZcu6Q/epBoKZfUs/IKHHy18COsW1GS9eU/Cdc0pCIlQGcMnGD4iOjuyIZCeXC5XQr7w3eI5GLz1BROC3RDvPpto3PGqbD7o7nUUxfDjY2nQ/xdiPsYrXg5DOeA0C1gtrPfN7OcKE1PeWU7KzwTK93QAshoiy+wQM5HZ5jPPQzgJkht23piCoqGIXmlziAZy/AZD+zyOp2v18LFksOvRBpmUI3SV8O6ZfGPA9Ih/ySn02iX8SvpEoUxYpUp8jcG0O91u8n7HWOxbtL7JXfT9vdYXIue7IaqFCFkeigeu6Eig/GSdPGlesiuTbn4E/s8cyXOwxjuE0Y7ReLWBJEhgjmHKaG7X909OSp1kSKc7vaa2yHBTlxalAjn3u+GDe9YC5d54A07M0kFAVSieRJKMU="
